### ISSUE TITLE
[mdc-101] Missing CSS rule in page #2

### ISSUE THREAD

**Issue by Aymkdn** [material-components/material-components-web-codelabs#32]
Hi,

On https://codelabs.developers.google.com/codelabs/mdc-101-web/#2 the provided example should look like this:
![capture](https://user-images.githubusercontent.com/946315/40043971-51ff83fe-5826-11e8-8d49-4ba3809b8b1c.PNG)

However it looks like the below (in both Chrome and Firefox):
![capture](https://user-images.githubusercontent.com/946315/40044012-760a3302-5826-11e8-81c9-f220cb6a5977.PNG)

The `label` are centered.

It might be confusing for a newbee. To fix it, in `app.scss`, you need to add `text-align:left`:
```css
.username,
.password {
  display: block;
  width: 300px;
  margin: 20px auto;
  text-align: left; /* rule to add in the tutorial */
}
```
