### ISSUE TITLE
[codelab] <Not able to use divider as shown in code>

### ISSUE THREAD

**Issue by soulehshaikh99** [material-components/material-components-web-codelabs#48]
In the completed pack of MDC-103 divider is not visible inspite of code written for it, Please solve this problem as fast as possible.
![error](https://user-images.githubusercontent.com/39525716/42734849-4eb1b826-8868-11e8-8b8d-f60ae6938a5e.PNG)

**Comment by williamernest** [comment]
@soulehshaikh99 I just ran through the codelab and the element does appear as expected. Can you verify that you added the element to your home.html and added the class to your app.scss?

```html
<li class="shrine-select-item-divider mdc-list-divider" role="separator"></li>
```
```scss
.shrine-select-item-divider {
  border-bottom-color: #EAA4A4;
  width: 50px;
  margin: 0 auto;
  border-bottom-width: 2px;
  position: relative;
  top: -5px;
}
```
